package com.util;
// Generated 03/01/2015 10:14:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private byte idgenero;
     private String nomgenero;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Genero() {
    }

	
    public Genero(byte idgenero, String nomgenero) {
        this.idgenero = idgenero;
        this.nomgenero = nomgenero;
    }
    public Genero(byte idgenero, String nomgenero, Set<Pelicula> peliculas) {
       this.idgenero = idgenero;
       this.nomgenero = nomgenero;
       this.peliculas = peliculas;
    }
   
    public byte getIdgenero() {
        return this.idgenero;
    }
    
    public void setIdgenero(byte idgenero) {
        this.idgenero = idgenero;
    }
    public String getNomgenero() {
        return this.nomgenero;
    }
    
    public void setNomgenero(String nomgenero) {
        this.nomgenero = nomgenero;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


