package com.util;
// Generated 03/01/2015 10:14:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private int idruta;
     private String ruta;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Ruta() {
    }

	
    public Ruta(int idruta, String ruta) {
        this.idruta = idruta;
        this.ruta = ruta;
    }
    public Ruta(int idruta, String ruta, Set<Pelicula> peliculas) {
       this.idruta = idruta;
       this.ruta = ruta;
       this.peliculas = peliculas;
    }
   
    public int getIdruta() {
        return this.idruta;
    }
    
    public void setIdruta(int idruta) {
        this.idruta = idruta;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


