package com.Entidad;
// Generated 03/01/2015 10:14:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private byte idcategoria;
     private String nomcategoria;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);

    public Categoria() {
    }

	
    public Categoria(byte idcategoria, String nomcategoria) {
        this.idcategoria = idcategoria;
        this.nomcategoria = nomcategoria;
    }
    public Categoria(byte idcategoria, String nomcategoria, Set<Pelicula> peliculas) {
       this.idcategoria = idcategoria;
       this.nomcategoria = nomcategoria;
       this.peliculas = peliculas;
    }
   
    public byte getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(byte idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNomcategoria() {
        return this.nomcategoria;
    }
    
    public void setNomcategoria(String nomcategoria) {
        this.nomcategoria = nomcategoria;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }




}


