package com.Entidad;
// Generated 03/01/2015 10:14:14 PM by Hibernate Tools 4.3.1



/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private int idpelicula;
     private Genero genero;
     private Ruta ruta;
     private Categoria categoria;
     private String nompelicula;

    public Pelicula() {
    }

    public Pelicula(int idpelicula, Genero genero, Ruta ruta, Categoria categoria, String nompelicula) {
       this.idpelicula = idpelicula;
       this.genero = genero;
       this.ruta = ruta;
       this.categoria = categoria;
       this.nompelicula = nompelicula;
    }
   
    public int getIdpelicula() {
        return this.idpelicula;
    }
    
    public void setIdpelicula(int idpelicula) {
        this.idpelicula = idpelicula;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNompelicula() {
        return this.nompelicula;
    }
    
    public void setNompelicula(String nompelicula) {
        this.nompelicula = nompelicula;
    }




}


